---
- name: Enable systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: started
    enabled: yes

- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart systemd-timesyncd
